sonar.projectKey=jtsato_corporate-code-generator
sonar.organization=jtsato

sonar.projectName=corporate-code-generator
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=packages,profiles,template-packs,examples
sonar.tests=packages,tests

sonar.exclusions=**/dist/**,**/node_modules/**,**/coverage/**,**/reports/**,**/generated/**,tests/golden/**

sonar.test.inclusions=**/*.test.ts,tests/**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info