import { describe, expect, it } from "vitest";
import { JavaSpringCleanMultimoduleCoreArtifactProducer } from "../src/index.js";

describe("JavaSpringCleanMultimoduleCoreArtifactProducer", () => {
  it("produces deterministic core domain, port, use case and interactor invocations", () => {
    const producer = new JavaSpringCleanMultimoduleCoreArtifactProducer();
    const artifacts = producer.produce({
      application: {
        schemaVersion: "1.0",
        name: "wallet-service",
        namespace: "io.github.jtsato.walletservice",
        entities: [{
          name: "Wallet",
          attributes: [
            { name: "id", type: "uuid", required: true, identifier: true },
            { name: "balance", type: "decimal", required: true, identifier: false },
          ],
        }],
      },
      profile: {
        id: "java-spring-clean-multimodule",
        version: "0.1.0",
        technology: {
          language: "java",
          languageVersion: "25",
          framework: "spring-boot",
        },
        architecture: { style: "clean-architecture" },
        templatePack: {
          id: "java-spring-clean-multimodule",
          version: "0.1.0",
        },
        modules: [{ id: "core", requires: [] }],
      },
      modules: [{ id: "core", requires: [] }],
    });

    expect(producer.profileId).toBe("java-spring-clean-multimodule");
    expect(producer.moduleId).toBe("core");
    expect(artifacts).toMatchObject([
      {
        templateId: "core-domain-entity",
        outputVariables: {
          packagePath: "io/github/jtsato/walletservice",
          domainName: "wallet",
          className: "Wallet",
        },
        model: {
          packageName: "io.github.jtsato.walletservice.core.domains.wallet.model",
          fields: [
            { name: "id", type: "UUID", modifiers: ["private", "final"], validationAnnotation: "@NotNull" },
            { name: "balance", type: "BigDecimal", modifiers: ["private", "final"], validationAnnotation: "@NotNull" },
          ],
          imports: [
            "io.github.jtsato.walletservice.core.common.validation.SelfValidating",
            "jakarta.validation.constraints.NotNull",
            "java.math.BigDecimal",
            "java.util.UUID",
          ],
          extendsType: "SelfValidating<Wallet>",
          validateSelf: true,
        },
      },
      {
        templateId: "core-gateway",
        outputVariables: { className: "WalletGateway" },
        model: {
          packageName: "io.github.jtsato.walletservice.core.domains.wallet.gateway",
          imports: [
            "io.github.jtsato.walletservice.core.common.filter.FilterExpression",
            "io.github.jtsato.walletservice.core.common.paging.PageRequest",
            "io.github.jtsato.walletservice.core.common.paging.PageResult",
            "io.github.jtsato.walletservice.core.domains.wallet.model.Wallet",
            "java.util.List",
            "java.util.UUID",
          ],
          interfaceName: "WalletGateway",
          entityType: "Wallet",
          findAllMethodName: "findAll",
          findByFilterMethodName: "findByFilter",
          filterExpressionType: "FilterExpression",
          filterExpressionParameterName: "filterExpression",
          findPageMethodName: "findPage",
          findByFilterPageMethodName: "findByFilterPage",
          pageRequestType: "PageRequest",
          pageRequestParameterName: "pageRequest",
          pageResultType: "PageResult",
        },
      },
      { templateId: "core-create-command" },
      { templateId: "core-create-usecase" },
      { templateId: "core-create-usecase-interactor" },
      { templateId: "core-create-usecase-interactor-test" },
      { templateId: "core-update-command" },
      { templateId: "core-update-usecase" },
      { templateId: "core-update-usecase-interactor" },
      { templateId: "core-update-usecase-interactor-test" },
      {
        templateId: "core-find-usecase",
        outputVariables: { className: "FindWalletsUseCase" },
        model: {
          interfaceName: "FindWalletsUseCase",
          entityType: "Wallet",
          executeMethodName: "execute",
        },
      },
      {
        templateId: "core-find-usecase-interactor",
        outputVariables: { className: "FindWalletsUseCaseInteractor" },
        model: {
          className: "FindWalletsUseCaseInteractor",
          interfaceName: "FindWalletsUseCase",
          gatewayType: "WalletGateway",
          gatewayFieldName: "walletGateway",
          entityType: "Wallet",
          executeMethodName: "execute",
          gatewayFindAllMethodName: "findAll",
        },
      },
      {
        templateId: "core-find-usecase-by-id",
        outputVariables: { className: "FindWalletByIdUseCase" },
        model: {
          interfaceName: "FindWalletByIdUseCase",
          entityType: "Wallet",
          identifierType: "UUID",
          identifierParameterName: "id",
          executeMethodName: "execute",
        },
      },
      {
        templateId: "core-find-usecase-by-id-interactor",
        outputVariables: { className: "FindWalletByIdUseCaseInteractor" },
        model: {
          className: "FindWalletByIdUseCaseInteractor",
          interfaceName: "FindWalletByIdUseCase",
          gatewayType: "WalletGateway",
          gatewayFieldName: "walletGateway",
          entityType: "Wallet",
          identifierType: "UUID",
          identifierParameterName: "id",
          executeMethodName: "execute",
          gatewayFindByIdMethodName: "findById",
          requiredMessageKey: "common.identifier.required",
          requiredDefaultMessage: "Identifier is required.",
        },
      },
      {
        templateId: "core-find-usecase-by-id-interactor-test",
        outputVariables: { className: "FindWalletByIdUseCaseInteractorTests" },
        model: {
          className: "FindWalletByIdUseCaseInteractorTests",
          interactorType: "FindWalletByIdUseCaseInteractor",
          gatewayType: "WalletGateway",
          entityType: "Wallet",
          identifierType: "UUID",
          identifierParameterName: "id",
          gatewayFindByIdMethodName: "findById",
          requiredMessageKey: "common.identifier.required",
        },
      },
      {
        templateId: "core-find-usecase-by-filter",
        outputVariables: { className: "FindWalletsByFilterUseCase" },
        model: {
          interfaceName: "FindWalletsByFilterUseCase",
          entityType: "Wallet",
          executeMethodName: "execute",
          filterExpressionType: "FilterExpression",
          filterExpressionParameterName: "filterExpression",
        },
      },
      {
        templateId: "core-find-usecase-by-filter-interactor",
        outputVariables: { className: "FindWalletsByFilterUseCaseInteractor" },
        model: {
          className: "FindWalletsByFilterUseCaseInteractor",
          interfaceName: "FindWalletsByFilterUseCase",
          gatewayType: "WalletGateway",
          gatewayFieldName: "walletGateway",
          entityType: "Wallet",
          executeMethodName: "execute",
          gatewayFindByFilterMethodName: "findByFilter",
          filterExpressionType: "FilterExpression",
          filterExpressionParameterName: "filterExpression",
          requiredMessageKey: "common.filter.expression.required",
          requiredDefaultMessage: "Filter expression is required.",
        },
      },
      {
        templateId: "core-find-usecase-by-filter-interactor-test",
        outputVariables: { className: "FindWalletsByFilterUseCaseInteractorTests" },
        model: {
          className: "FindWalletsByFilterUseCaseInteractorTests",
          interactorType: "FindWalletsByFilterUseCaseInteractor",
          fakeGatewayType: "FakeWalletGateway",
          gatewayType: "WalletGateway",
          entityType: "Wallet",
          gatewayFindAllMethodName: "findAll",
          gatewayFindByFilterMethodName: "findByFilter",
          filterExpressionType: "FilterExpression",
          filterExpressionParameterName: "filterExpression",
          requiredMessageKey: "common.filter.expression.required",
          sampleFieldName: "id",
          gatewayFindPageMethodName: "findPage",
          gatewayFindByFilterPageMethodName: "findByFilterPage",
          pageRequestType: "PageRequest",
          pageRequestParameterName: "pageRequest",
          pageResultType: "PageResult",
        },
      },
      {
        templateId: "core-find-usecase-by-filter-page",
        outputVariables: { className: "FindWalletsByFilterPageUseCase" },
        model: {
          interfaceName: "FindWalletsByFilterPageUseCase",
          entityType: "Wallet",
          executeMethodName: "execute",
          filterExpressionType: "FilterExpression",
          filterExpressionParameterName: "filterExpression",
          pageRequestType: "PageRequest",
          pageRequestParameterName: "pageRequest",
          pageResultType: "PageResult",
        },
      },
      {
        templateId: "core-find-usecase-by-filter-page-interactor",
        outputVariables: { className: "FindWalletsByFilterPageUseCaseInteractor" },
        model: {
          className: "FindWalletsByFilterPageUseCaseInteractor",
          interfaceName: "FindWalletsByFilterPageUseCase",
          gatewayType: "WalletGateway",
          gatewayFieldName: "walletGateway",
          entityType: "Wallet",
          executeMethodName: "execute",
          gatewayFindByFilterPageMethodName: "findByFilterPage",
          filterExpressionType: "FilterExpression",
          filterExpressionParameterName: "filterExpression",
          pageRequestType: "PageRequest",
          pageRequestParameterName: "pageRequest",
          pageResultType: "PageResult",
          requiredFilterMessageKey: "common.filter.expression.required",
          requiredFilterDefaultMessage: "Filter expression is required.",
          requiredPageMessageKey: "common.paging.page-request.required",
          requiredPageDefaultMessage: "Page request is required.",
        },
      },
      {
        templateId: "core-find-usecase-by-filter-page-interactor-test",
        outputVariables: { className: "FindWalletsByFilterPageUseCaseInteractorTests" },
        model: {
          className: "FindWalletsByFilterPageUseCaseInteractorTests",
          interactorType: "FindWalletsByFilterPageUseCaseInteractor",
          fakeGatewayType: "FakeWalletGateway",
          gatewayType: "WalletGateway",
          entityType: "Wallet",
          gatewayFindAllMethodName: "findAll",
          gatewayFindByFilterMethodName: "findByFilter",
          gatewayFindPageMethodName: "findPage",
          gatewayFindByFilterPageMethodName: "findByFilterPage",
          filterExpressionType: "FilterExpression",
          filterExpressionParameterName: "filterExpression",
          pageRequestType: "PageRequest",
          pageRequestParameterName: "pageRequest",
          pageResultType: "PageResult",
          requiredFilterMessageKey: "common.filter.expression.required",
          requiredPageMessageKey: "common.paging.page-request.required",
          sampleFieldName: "id",
        },
      },
      {
        templateId: "core-find-usecase-page",
        outputVariables: { className: "FindWalletsPageUseCase" },
        model: {
          interfaceName: "FindWalletsPageUseCase",
          entityType: "Wallet",
          executeMethodName: "execute",
          pageRequestType: "PageRequest",
          pageRequestParameterName: "pageRequest",
          pageResultType: "PageResult",
        },
      },
      {
        templateId: "core-find-usecase-page-interactor",
        outputVariables: { className: "FindWalletsPageUseCaseInteractor" },
        model: {
          className: "FindWalletsPageUseCaseInteractor",
          interfaceName: "FindWalletsPageUseCase",
          gatewayType: "WalletGateway",
          gatewayFieldName: "walletGateway",
          entityType: "Wallet",
          executeMethodName: "execute",
          gatewayFindPageMethodName: "findPage",
          pageRequestType: "PageRequest",
          pageRequestParameterName: "pageRequest",
          pageResultType: "PageResult",
          requiredMessageKey: "common.paging.page-request.required",
          requiredDefaultMessage: "Page request is required.",
        },
      },
      {
        templateId: "core-find-usecase-page-interactor-test",
        outputVariables: { className: "FindWalletsPageUseCaseInteractorTests" },
        model: {
          className: "FindWalletsPageUseCaseInteractorTests",
          interactorType: "FindWalletsPageUseCaseInteractor",
          fakeGatewayType: "FakeWalletGateway",
          gatewayType: "WalletGateway",
          entityType: "Wallet",
          gatewayFindAllMethodName: "findAll",
          gatewayFindByFilterMethodName: "findByFilter",
          gatewayFindPageMethodName: "findPage",
          filterExpressionType: "FilterExpression",
          filterExpressionParameterName: "filterExpression",
          pageRequestType: "PageRequest",
          pageRequestParameterName: "pageRequest",
          pageResultType: "PageResult",
          requiredMessageKey: "common.paging.page-request.required",
        },
      },
      { templateId: "core-application-exception", outputVariables: { packagePath: "io/github/jtsato/walletservice", className: "ApplicationException" }, model: { packageName: "io.github.jtsato.walletservice.core.common.exception", className: "ApplicationException" } },
      { templateId: "core-field-violation", outputVariables: { packagePath: "io/github/jtsato/walletservice", className: "FieldViolation" }, model: { packageName: "io.github.jtsato.walletservice.core.common.exception", className: "FieldViolation" } },
      { templateId: "core-validation-exception", outputVariables: { packagePath: "io/github/jtsato/walletservice", className: "ValidationException" }, model: { packageName: "io.github.jtsato.walletservice.core.common.exception", className: "ValidationException", parentClassName: "ApplicationException", fieldViolationClassName: "FieldViolation" } },
      { templateId: "core-not-found-exception", outputVariables: { packagePath: "io/github/jtsato/walletservice", className: "NotFoundException" }, model: { packageName: "io.github.jtsato.walletservice.core.common.exception", className: "NotFoundException", parentClassName: "ApplicationException" } },
      { templateId: "core-conflict-exception", outputVariables: { packagePath: "io/github/jtsato/walletservice", className: "ConflictException" }, model: { packageName: "io.github.jtsato.walletservice.core.common.exception", className: "ConflictException", parentClassName: "ApplicationException" } },
      { templateId: "core-self-validating", outputVariables: { packagePath: "io/github/jtsato/walletservice", className: "SelfValidating" }, model: { packageName: "io.github.jtsato.walletservice.core.common.validation", exceptionPackage: "io.github.jtsato.walletservice.core.common.exception" } },
      { templateId: "core-sort-direction", outputVariables: { packagePath: "io/github/jtsato/walletservice", className: "SortDirection" }, model: { packageName: "io.github.jtsato.walletservice.core.common.paging" } },
      { templateId: "core-sort-order", outputVariables: { packagePath: "io/github/jtsato/walletservice", className: "SortOrder" }, model: { packageName: "io.github.jtsato.walletservice.core.common.paging" } },
      { templateId: "core-page-request", outputVariables: { packagePath: "io/github/jtsato/walletservice", className: "PageRequest" }, model: { packageName: "io.github.jtsato.walletservice.core.common.paging" } },
      { templateId: "core-page-result", outputVariables: { packagePath: "io/github/jtsato/walletservice", className: "PageResult" }, model: { packageName: "io.github.jtsato.walletservice.core.common.paging" } },
      { templateId: "core-domain-validation-test", outputVariables: { packagePath: "io/github/jtsato/walletservice", domainName: "wallet", className: "WalletValidationTests" }, model: { packageName: "io.github.jtsato.walletservice.core.domains.wallet.model", exceptionPackage: "io.github.jtsato.walletservice.core.common.exception", className: "WalletValidationTests", entityType: "Wallet", requiredFieldNames: ["balance", "id"] } },
      { templateId: "core-sort-order-test", outputVariables: { packagePath: "io/github/jtsato/walletservice", className: "SortOrderTests" }, model: { packageName: "io.github.jtsato.walletservice.core.common.paging" } },
      { templateId: "core-page-request-test", outputVariables: { packagePath: "io/github/jtsato/walletservice", className: "PageRequestTests" }, model: { packageName: "io.github.jtsato.walletservice.core.common.paging" } },
      { templateId: "core-page-result-test", outputVariables: { packagePath: "io/github/jtsato/walletservice", className: "PageResultTests" }, model: { packageName: "io.github.jtsato.walletservice.core.common.paging" } },
      { templateId: "core-filter-operator", outputVariables: { packagePath: "io/github/jtsato/walletservice", className: "FilterOperator" }, model: { packageName: "io.github.jtsato.walletservice.core.common.filter", exceptionPackage: "io.github.jtsato.walletservice.core.common.exception", className: "FilterOperator" } },
      { templateId: "core-filter-condition", outputVariables: { packagePath: "io/github/jtsato/walletservice", className: "FilterCondition" }, model: { packageName: "io.github.jtsato.walletservice.core.common.filter", exceptionPackage: "io.github.jtsato.walletservice.core.common.exception", className: "FilterCondition" } },
      { templateId: "core-filter-group-operator", outputVariables: { packagePath: "io/github/jtsato/walletservice", className: "FilterGroupOperator" }, model: { packageName: "io.github.jtsato.walletservice.core.common.filter", exceptionPackage: "io.github.jtsato.walletservice.core.common.exception", className: "FilterGroupOperator" } },
      { templateId: "core-filter-group", outputVariables: { packagePath: "io/github/jtsato/walletservice", className: "FilterGroup" }, model: { packageName: "io.github.jtsato.walletservice.core.common.filter", exceptionPackage: "io.github.jtsato.walletservice.core.common.exception", className: "FilterGroup" } },
      { templateId: "core-filter-expression", outputVariables: { packagePath: "io/github/jtsato/walletservice", className: "FilterExpression" }, model: { packageName: "io.github.jtsato.walletservice.core.common.filter", exceptionPackage: "io.github.jtsato.walletservice.core.common.exception", className: "FilterExpression" } },
      { templateId: "core-filter-condition-test", outputVariables: { packagePath: "io/github/jtsato/walletservice", className: "FilterConditionTests" }, model: { packageName: "io.github.jtsato.walletservice.core.common.filter", exceptionPackage: "io.github.jtsato.walletservice.core.common.exception", className: "FilterConditionTests", typeName: "FilterCondition" } },
      { templateId: "core-filter-group-test", outputVariables: { packagePath: "io/github/jtsato/walletservice", className: "FilterGroupTests" }, model: { packageName: "io.github.jtsato.walletservice.core.common.filter", exceptionPackage: "io.github.jtsato.walletservice.core.common.exception", className: "FilterGroupTests", typeName: "FilterGroup" } },
      { templateId: "core-filter-expression-test", outputVariables: { packagePath: "io/github/jtsato/walletservice", className: "FilterExpressionTests" }, model: { packageName: "io.github.jtsato.walletservice.core.common.filter", exceptionPackage: "io.github.jtsato.walletservice.core.common.exception", className: "FilterExpressionTests", typeName: "FilterExpression" } },
    ]);
  });
});
