export interface JavaPatchUseCaseInteractorTestTemplateModel {
  readonly packageName: string;
  readonly imports: readonly string[];
  readonly className: string;
  readonly interactorType: string;
  readonly fakeGatewayType: string;
  readonly gatewayType: string;
  readonly entityType: string;
  readonly commandType: string;
  readonly identifierType: string;
  readonly currentEntityArguments: readonly string[];
  readonly commandArguments: readonly string[];
  readonly updatedCommandArguments: readonly string[];
  readonly fieldAssertions: readonly { readonly accessorName: string; readonly expectedExpression: string }[];
  readonly updatedFieldAssertions: readonly { readonly accessorName: string; readonly expectedExpression: string }[];
  readonly requiredFields: readonly { readonly fieldName: string; readonly messageKey: string; readonly testMethodSuffix: string; readonly nullArguments: readonly string[] }[];
  readonly emptyCommandArguments: readonly string[];
  readonly executeMethodName: string;
  readonly gatewayFindByIdMethodName: string;
  readonly gatewayUpdateMethodName: string;
  readonly commandRequiredMessageKey: string;
  readonly atLeastOneFieldMessageKey: string;
  readonly hasOptionalNullScenario: boolean;
  readonly optionalNullFieldName: string;
  readonly optionalNullCommandArguments: readonly string[];
  readonly hasOmittedFieldScenario: boolean;
  readonly omittedFieldName: string;
  readonly omittedExpectedExpression: string;
  readonly omittedCommandArguments: readonly string[];
}
