export interface JavaGatewayProviderTemplateModel {
  readonly packageName: string;
  readonly imports: readonly string[];
  readonly className: string;
  readonly gatewayType: string;
  readonly entityType: string;
  readonly findAllMethodName: string;
  readonly repositoryType: string;
  readonly repositoryFieldName: string;
  readonly constructorName: string;
  readonly mapperType: string;
  readonly repositoryFindAllMethodName: string;
  readonly mapperToDomainMethodName: string;
  readonly identifierType: string;
  readonly identifierParameterName: string;
  readonly findByIdMethodName: string;
  readonly repositoryFindByIdMethodName: string;
  readonly notFoundExceptionType: string;
  readonly notFoundMessageKey: string;
  readonly notFoundDefaultMessage: string;
  readonly findByFilterMethodName: string;
  readonly filterExpressionType: string;
  readonly filterExpressionParameterName: string;
  readonly filterMapperType: string;
  readonly filterMapperMethodName: string;
  readonly filterDefinitionType: string;
  readonly filterDefinitionFactoryMethodName: string;
  readonly findByFilterPageMethodName: string;
  readonly persistenceEntityType: string;
  readonly persistenceEntitiesVariableName: string;
  readonly requiresIterableConversion: boolean;
  readonly findPageMethodName: string;
  readonly pageRequestType: string;
  readonly pageRequestParameterName: string;
  readonly pageResultType: string;
  readonly pageableType: string;
  readonly pageableVariableName: string;
  readonly pageType: string;
  readonly pageVariableName: string;
  readonly pageRequestMapperType: string;
  readonly pageRequestMapperMethodName: string;
  readonly pageResultMapperType: string;
  readonly pageResultMapperMethodName: string;
  readonly sortPropertyMapping: readonly {
    readonly domainName: string;
    readonly persistenceName: string;
  }[];
  readonly createMethodName: string;
  readonly createParameterName: string;
  readonly repositorySaveMethodName: string;
  readonly mapperToEntityMethodName: string;
  readonly identifierAccessorName: string;
  readonly repositoryExistsByIdMethodName: string;
  readonly conflictExceptionType: string;
  readonly conflictMessageKey: string;
  readonly conflictDefaultMessage: string;
  readonly updateMethodName: string;
  readonly updateParameterName: string;
  readonly deleteMethodName: string;
  readonly deleteParameterName: string;
  readonly repositoryDeleteByIdMethodName: string;
  readonly querydslEntityVariableName: string;
  readonly activeScopeConstantReference: string;
  readonly activePredicateMethodName: string;
  readonly uniqueChecks: readonly {
    readonly domainAccessorName: string;
    readonly persistenceFieldName: string;
  }[];
  readonly identifierPersistenceFieldName: string;
  readonly persistenceEntityActiveMethodName: string;
  readonly persistenceEntityMarkDeletedMethodName: string;
  readonly repositoryExistsMethodName: string;
}
